export const ruteAset = {
  index: '/aset',
  garansiDetail: (id: string) => `/aset/garansi/${id}`,
  meterPembacaan: (id: string) => `/aset/meter/${id}/pembacaan`,
  relasiDetail: (id: string) => `/aset/relasi/${id}`,
  detail: (id: string) => `/aset/${id}`,
  kelayakan: (id: string) => `/aset/${id}/kelayakan`,
  kartuRiwayat: (id: string) => `/aset/${id}/kartu-riwayat`,
  /** Galeri foto aset (PRD 8.4): unggah (POST, `Foto[]`), jadikan utama (PUT), hapus (DELETE). */
  foto: (id: string) => `/aset/${id}/foto`,
  fotoDetail: (id: string, berkasId: string) => `/aset/${id}/foto/${berkasId}`,
  fotoUtama: (id: string, berkasId: string) => `/aset/${id}/foto/${berkasId}/utama`,
  kelayakanIndex: '/aset/kelayakan',
  garansi: (id: string) => `/aset/${id}/garansi`,
  meter: (id: string) => `/aset/${id}/meter`,
  nilai: (id: string) => `/aset/${id}/nilai`,
  nilaiPratinjau: (id: string) => `/aset/${id}/nilai/pratinjau`,
  penanggungJawab: (id: string) => `/aset/${id}/penanggung-jawab`,
  relasi: (id: string) => `/aset/${id}/relasi`,
  riwayatLokasi: (id: string) => `/aset/${id}/riwayat-lokasi`,
  riwayatLokasiEkspor: (id: string) => `/aset/${id}/riwayat-lokasi/ekspor`,
  riwayatPemeliharaan: (id: string) => `/aset/${id}/riwayat-pemeliharaan`,
  riwayatKalibrasi: (id: string) => `/aset/${id}/riwayat-kalibrasi`,
  label: (id: string[]) => `/aset/label?${id.map((satu) => `id[]=${encodeURIComponent(satu)}`).join('&')}`,
  ekspor: '/aset/ekspor',
  unitPengelola: '/aset/unit-pengelola',
  imporTemplat: (format: 'csv' | 'xlsx') => `/aset/impor/templat?format=${format}`,
  imporPratinjau: '/aset/impor/pratinjau',
  imporGalat: '/aset/impor/galat',
  impor: '/aset/impor',
};
